#ifndef FRONTEND_LEXER_TOKENS_TOKENKIND_H_
#define FRONTEND_LEXER_TOKENS_TOKENKIND_H_

typedef enum tokenkind_t
{
    TK_PLUS,
    TK_MINUS,
    TK_ASTERISK,
    TK_EXP,
    TK_FSLASH,
    TK_PERCENT,
    TK_LPAREN,
    TK_RPAREN,
    TK_LBRACE,
    TK_RBRACE,
    TK_SEMICOLON,
    TK_EQ,
    TK_EQEQ,
    TK_NOT,
    TK_AND,
    TK_OR,
    TK_XOR,
    TK_NEQ,
    TK_LT,
    TK_LE,
    TK_GT,
    TK_GE,
    TK_NUMBER,
    TK_IDENTIFIER,
    TK_TRUE,
    TK_FALSE,
    TK_IF,
    TK_UNLESS,
    TK_ELIF,
    TK_ELSE,
    TK_WHILE,
    TK_UNTIL,
    TK_FOREVER,
    TK_REPEAT,
    TK_STOP,
    TK_SKIP,
    TK_ONSTOP,
    TK_NOSTOP,
    TK_FUNCTION,
    TK_RETURN,
    TK_RETURNS,
    TK_COMMA,
    TK_EOF,
} TokenKind;

#endif